spring: 
  #jdbc配置
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/wf
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#mybatis配置
mybatis:
#实体类所在包名
  type-aliases-package: testSite.models
  configuration: 
     map-underscore-to-camel-case: true
#通用mapper配置
mapper:
  #公用接口类路径
  mappers: testSite.BaseRepository
  identity: MYSQL
